abbr gst='git status'
abbr gd='git diff'
abbr gl='git pull'
abbr glo='git pull origin'
abbr gp='git push'
abbr gpo='git push origin'
abbr gcmsg='git commit -m'
abbr gco='git checkout'
abbr gcm='git checkout master'
abbr glg='git log --stat --max-count=10'
abbr ga='git add'
abbr gaa='git add .'
abbr gsta='git stash'
abbr gstaa='git stash apply'

